actions:
  metadata:
    name: ibmcloudEnablement
    description: "Installation for IBM Cloud"
  actionDefs:
    preInstall:
      metadata:
        name: preInstall
        description: "Prerequisites to installing Mobile Foundation"
      roles:
      - clusterAdmin
      requires:
        "/case/prereqs/k8sDistros/openshift"
      k8sPermissions:
        rules:
        - rule:
            group: "*"
            resource: "*"
            verbs:
            - "*"

    install:
      metadata:
        name: install
        description: "Install the Mobile Foundation"
      roles:
      - clusterAdmin
      requires:
        "/case/prereqs/k8sDistros/openshift"
      k8sPermissions:
        rules:
        - rule:
            group: "*"
            resource: "*"
            verbs:
            - "*"