###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2019. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
# IBM Corporation - initial API and implementation
###############################################################################
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: db2operators.db2.ibm.com
  labels:
    app.kubernetes.io/name: db2-operator
    app.kubernetes.io/instance: db2-instance
    app.kubernetes.io/managed-by: helm
    release: db2-operator-_IMG_TAG_
spec:
  group: db2.ibm.com
  names:
    kind: DB2Operator
    listKind: DB2OperatorList
    plural: db2operators
    shortNames:
    - db2
    singular: db2operator
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object